/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.customer.support.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the support service. Represents a row in the &quot;panasonic_support&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.customer.support.model.impl.supportModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.customer.support.model.impl.supportImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see support
 * @generated
 */
@ProviderType
public interface supportModel extends BaseModel<support> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support model instance should use the {@link support} interface instead.
	 */

	/**
	 * Returns the primary key of this support.
	 *
	 * @return the primary key of this support
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support.
	 *
	 * @param primaryKey the primary key of this support
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the spport ID of this support.
	 *
	 * @return the spport ID of this support
	 */
	public long getSpportId();

	/**
	 * Sets the spport ID of this support.
	 *
	 * @param spportId the spport ID of this support
	 */
	public void setSpportId(long spportId);

	/**
	 * Returns the claim of this support.
	 *
	 * @return the claim of this support
	 */
	@AutoEscape
	public String getClaim();

	/**
	 * Sets the claim of this support.
	 *
	 * @param claim the claim of this support
	 */
	public void setClaim(String claim);

	/**
	 * Returns the query of this support.
	 *
	 * @return the query of this support
	 */
	@AutoEscape
	public String getQuery();

	/**
	 * Sets the query of this support.
	 *
	 * @param query the query of this support
	 */
	public void setQuery(String query);

	/**
	 * Returns the suggestioncomplaint of this support.
	 *
	 * @return the suggestioncomplaint of this support
	 */
	@AutoEscape
	public String getSuggestioncomplaint();

	/**
	 * Sets the suggestioncomplaint of this support.
	 *
	 * @param suggestioncomplaint the suggestioncomplaint of this support
	 */
	public void setSuggestioncomplaint(String suggestioncomplaint);

	/**
	 * Returns the bu of this support.
	 *
	 * @return the bu of this support
	 */
	@AutoEscape
	public String getBU();

	/**
	 * Sets the bu of this support.
	 *
	 * @param BU the bu of this support
	 */
	public void setBU(String BU);

	/**
	 * Returns the channel of this support.
	 *
	 * @return the channel of this support
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this support.
	 *
	 * @param channel the channel of this support
	 */
	public void setChannel(String channel);

	/**
	 * Returns the invoice number of this support.
	 *
	 * @return the invoice number of this support
	 */
	public long getInvoiceNumber();

	/**
	 * Sets the invoice number of this support.
	 *
	 * @param invoiceNumber the invoice number of this support
	 */
	public void setInvoiceNumber(long invoiceNumber);

	/**
	 * Returns the invoice date of this support.
	 *
	 * @return the invoice date of this support
	 */
	public Date getInvoiceDate();

	/**
	 * Sets the invoice date of this support.
	 *
	 * @param invoiceDate the invoice date of this support
	 */
	public void setInvoiceDate(Date invoiceDate);

	/**
	 * Returns the item value invoice of this support.
	 *
	 * @return the item value invoice of this support
	 */
	public long getItemValueInvoice();

	/**
	 * Sets the item value invoice of this support.
	 *
	 * @param itemValueInvoice the item value invoice of this support
	 */
	public void setItemValueInvoice(long itemValueInvoice);

	/**
	 * Returns the item value you of this support.
	 *
	 * @return the item value you of this support
	 */
	public long getItemValueYou();

	/**
	 * Sets the item value you of this support.
	 *
	 * @param itemValueYou the item value you of this support
	 */
	public void setItemValueYou(long itemValueYou);

	/**
	 * Returns the claim value of this support.
	 *
	 * @return the claim value of this support
	 */
	public long getClaimValue();

	/**
	 * Sets the claim value of this support.
	 *
	 * @param claimValue the claim value of this support
	 */
	public void setClaimValue(long claimValue);

	/**
	 * Returns the detail claim of this support.
	 *
	 * @return the detail claim of this support
	 */
	@AutoEscape
	public String getDetailClaim();

	/**
	 * Sets the detail claim of this support.
	 *
	 * @param detailClaim the detail claim of this support
	 */
	public void setDetailClaim(String detailClaim);

	/**
	 * Returns the querybox of this support.
	 *
	 * @return the querybox of this support
	 */
	@AutoEscape
	public String getQuerybox();

	/**
	 * Sets the querybox of this support.
	 *
	 * @param querybox the querybox of this support
	 */
	public void setQuerybox(String querybox);

	/**
	 * Returns the sc box of this support.
	 *
	 * @return the sc box of this support
	 */
	@AutoEscape
	public String getScBox();

	/**
	 * Sets the sc box of this support.
	 *
	 * @param scBox the sc box of this support
	 */
	public void setScBox(String scBox);

}