/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package queries.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the answer service. Represents a row in the &quot;queries_answer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>queries.service.model.impl.answerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>queries.service.model.impl.answerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see answer
 * @generated
 */
@ProviderType
public interface answerModel extends BaseModel<answer> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a answer model instance should use the {@link answer} interface instead.
	 */

	/**
	 * Returns the primary key of this answer.
	 *
	 * @return the primary key of this answer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this answer.
	 *
	 * @param primaryKey the primary key of this answer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this answer.
	 *
	 * @return the uuid of this answer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this answer.
	 *
	 * @param uuid the uuid of this answer
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ans ID of this answer.
	 *
	 * @return the ans ID of this answer
	 */
	public long getAnsId();

	/**
	 * Sets the ans ID of this answer.
	 *
	 * @param ansId the ans ID of this answer
	 */
	public void setAnsId(long ansId);

	/**
	 * Returns the ans title of this answer.
	 *
	 * @return the ans title of this answer
	 */
	@AutoEscape
	public String getAnsTitle();

	/**
	 * Sets the ans title of this answer.
	 *
	 * @param ansTitle the ans title of this answer
	 */
	public void setAnsTitle(String ansTitle);

	/**
	 * Returns the ans desc of this answer.
	 *
	 * @return the ans desc of this answer
	 */
	@AutoEscape
	public String getAnsDesc();

	/**
	 * Sets the ans desc of this answer.
	 *
	 * @param ansDesc the ans desc of this answer
	 */
	public void setAnsDesc(String ansDesc);

	/**
	 * Returns the user name of this answer.
	 *
	 * @return the user name of this answer
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this answer.
	 *
	 * @param userName the user name of this answer
	 */
	public void setUserName(String userName);

	/**
	 * Returns the ques ID of this answer.
	 *
	 * @return the ques ID of this answer
	 */
	public long getQuesId();

	/**
	 * Sets the ques ID of this answer.
	 *
	 * @param quesId the ques ID of this answer
	 */
	public void setQuesId(long quesId);

	/**
	 * Returns the field1 of this answer.
	 *
	 * @return the field1 of this answer
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this answer.
	 *
	 * @param field1 the field1 of this answer
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this answer.
	 *
	 * @return the field2 of this answer
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this answer is field2.
	 *
	 * @return <code>true</code> if this answer is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this answer is field2.
	 *
	 * @param field2 the field2 of this answer
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this answer.
	 *
	 * @return the field3 of this answer
	 */
	public int getField3();

	/**
	 * Sets the field3 of this answer.
	 *
	 * @param field3 the field3 of this answer
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this answer.
	 *
	 * @return the field4 of this answer
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this answer.
	 *
	 * @param field4 the field4 of this answer
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this answer.
	 *
	 * @return the field5 of this answer
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this answer.
	 *
	 * @param field5 the field5 of this answer
	 */
	public void setField5(String field5);

}