/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package queries.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the question service. Represents a row in the &quot;queries_question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>queries.service.model.impl.questionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>queries.service.model.impl.questionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see question
 * @generated
 */
@ProviderType
public interface questionModel extends BaseModel<question> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question model instance should use the {@link question} interface instead.
	 */

	/**
	 * Returns the primary key of this question.
	 *
	 * @return the primary key of this question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question.
	 *
	 * @param primaryKey the primary key of this question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this question.
	 *
	 * @return the uuid of this question
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this question.
	 *
	 * @param uuid the uuid of this question
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ques ID of this question.
	 *
	 * @return the ques ID of this question
	 */
	public long getQuesId();

	/**
	 * Sets the ques ID of this question.
	 *
	 * @param quesId the ques ID of this question
	 */
	public void setQuesId(long quesId);

	/**
	 * Returns the ques title of this question.
	 *
	 * @return the ques title of this question
	 */
	@AutoEscape
	public String getQuesTitle();

	/**
	 * Sets the ques title of this question.
	 *
	 * @param quesTitle the ques title of this question
	 */
	public void setQuesTitle(String quesTitle);

	/**
	 * Returns the ques desc of this question.
	 *
	 * @return the ques desc of this question
	 */
	@AutoEscape
	public String getQuesDesc();

	/**
	 * Sets the ques desc of this question.
	 *
	 * @param quesDesc the ques desc of this question
	 */
	public void setQuesDesc(String quesDesc);

	/**
	 * Returns the user name of this question.
	 *
	 * @return the user name of this question
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this question.
	 *
	 * @param userName the user name of this question
	 */
	public void setUserName(String userName);

	/**
	 * Returns the field1 of this question.
	 *
	 * @return the field1 of this question
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this question.
	 *
	 * @param field1 the field1 of this question
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this question.
	 *
	 * @return the field2 of this question
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this question is field2.
	 *
	 * @return <code>true</code> if this question is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this question is field2.
	 *
	 * @param field2 the field2 of this question
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this question.
	 *
	 * @return the field3 of this question
	 */
	public int getField3();

	/**
	 * Sets the field3 of this question.
	 *
	 * @param field3 the field3 of this question
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this question.
	 *
	 * @return the field4 of this question
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this question.
	 *
	 * @param field4 the field4 of this question
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this question.
	 *
	 * @return the field5 of this question
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this question.
	 *
	 * @param field5 the field5 of this question
	 */
	public void setField5(String field5);

}