/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package panasonic.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the channel service. Represents a row in the &quot;Liferay_channel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>panasonic.service.model.impl.channelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>panasonic.service.model.impl.channelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see channel
 * @generated
 */
@ProviderType
public interface channelModel extends BaseModel<channel> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a channel model instance should use the {@link channel} interface instead.
	 */

	/**
	 * Returns the primary key of this channel.
	 *
	 * @return the primary key of this channel
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this channel.
	 *
	 * @param primaryKey the primary key of this channel
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this channel.
	 *
	 * @return the uuid of this channel
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this channel.
	 *
	 * @param uuid the uuid of this channel
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user name of this channel.
	 *
	 * @return the user name of this channel
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this channel.
	 *
	 * @param userName the user name of this channel
	 */
	public void setUserName(String userName);

	/**
	 * Returns the name of this channel.
	 *
	 * @return the name of this channel
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this channel.
	 *
	 * @param name the name of this channel
	 */
	public void setName(String name);

	/**
	 * Returns the email of this channel.
	 *
	 * @return the email of this channel
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this channel.
	 *
	 * @param email the email of this channel
	 */
	public void setEmail(String email);

	/**
	 * Returns the password of this channel.
	 *
	 * @return the password of this channel
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this channel.
	 *
	 * @param password the password of this channel
	 */
	public void setPassword(String password);

	/**
	 * Returns the otp of this channel.
	 *
	 * @return the otp of this channel
	 */
	@AutoEscape
	public String getOtp();

	/**
	 * Sets the otp of this channel.
	 *
	 * @param otp the otp of this channel
	 */
	public void setOtp(String otp);

	/**
	 * Returns the field1 of this channel.
	 *
	 * @return the field1 of this channel
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this channel.
	 *
	 * @param field1 the field1 of this channel
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this channel.
	 *
	 * @return the field2 of this channel
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this channel is field2.
	 *
	 * @return <code>true</code> if this channel is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this channel is field2.
	 *
	 * @param field2 the field2 of this channel
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this channel.
	 *
	 * @return the field3 of this channel
	 */
	public int getField3();

	/**
	 * Sets the field3 of this channel.
	 *
	 * @param field3 the field3 of this channel
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this channel.
	 *
	 * @return the field4 of this channel
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this channel.
	 *
	 * @param field4 the field4 of this channel
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this channel.
	 *
	 * @return the field5 of this channel
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this channel.
	 *
	 * @param field5 the field5 of this channel
	 */
	public void setField5(String field5);

}